# Generated by Django 2.1 on 2018-10-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='word',
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='word_examples',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='search.Example'),
        ),
        migrations.AddField(
            model_name='word',
            name='word_meaning',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='search.Meaning'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_text',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='word',
            name='word_origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='search.Origin'),
        ),
    ]
