# Generated by Django 2.1 on 2018-10-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181007_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
