# Generated by Django 2.1 on 2019-02-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_word_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_meaning',
        ),
        migrations.AddField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='search.Word'),
        ),
    ]
